---
baseurl: ""
defaults:
  -
    scope:
      path: assets/img
    values:
      image: true
description: "Documentação unificada dos repositórios.\n"
email: ctic.sje@listas.ifsc.edu.br
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
github_username: ctic-sje-ifsc
include:
  - _pages
theme: minima
title: "CTIC - SJE - IFSC"
url: "https://ctic-sje-ifsc.github.io/"
